const data = [
  {
    id: 2,
    title: "Classic Red Pullover Hoodie",
    slug: "classic-red-pullover-hoodie",
    price: 10,
    description:
      "Elevate your casual wardrobe with our Classic Red Pullover Hoodie. Crafted with a soft cotton blend for ultimate comfort, this vibrant red hoodie features a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs for a snug fit. The timeless design ensures easy pairing with jeans or joggers for a relaxed yet stylish look, making it a versatile addition to your everyday attire.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/1twoaDy.jpeg",
      "https://i.imgur.com/FDwQgLy.jpeg",
      "https://i.imgur.com/kg1ZhhH.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 4,
    title: "Classic Grey Hooded Sweatshirt",
    slug: "classic-grey-hooded-sweatshirt",
    price: 90,
    description:
      "Elevate your casual wear with our Classic Grey Hooded Sweatshirt. Made from a soft cotton blend, this hoodie features a front kangaroo pocket, an adjustable drawstring hood, and ribbed cuffs for a snug fit. Perfect for those chilly evenings or lazy weekends, it pairs effortlessly with your favorite jeans or joggers.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/R2PN9Wq.jpeg",
      "https://i.imgur.com/IvxMPFr.jpeg",
      "https://i.imgur.com/7eW9nXP.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 5,
    title: "Classic Black Hooded Sweatshirt",
    slug: "classic-black-hooded-sweatshirt",
    price: 79,
    description:
      "Elevate your casual wardrobe with our Classic Black Hooded Sweatshirt. Made from high-quality, soft fabric that ensures comfort and durability, this hoodie features a spacious kangaroo pocket and an adjustable drawstring hood. Its versatile design makes it perfect for a relaxed day at home or a casual outing.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/cSytoSD.jpeg",
      "https://i.imgur.com/WwKucXb.jpeg",
      "https://i.imgur.com/cE2Dxh9.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 6,
    title: "Classic Comfort Fit Joggers",
    slug: "classic-comfort-fit-joggers",
    price: 25,
    description:
      "Discover the perfect blend of style and comfort with our Classic Comfort Fit Joggers. These versatile black joggers feature a soft elastic waistband with an adjustable drawstring, two side pockets, and ribbed ankle cuffs for a secure fit. Made from a lightweight and durable fabric, they are ideal for both active days and relaxed lounging.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/ZKGofuB.jpeg",
      "https://i.imgur.com/GJi73H0.jpeg",
      "https://i.imgur.com/633Fqrz.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 8,
    title: "Classic Red Jogger Sweatpants",
    slug: "classic-red-jogger-sweatpants",
    price: 98,
    description:
      "Experience ultimate comfort with our red jogger sweatpants, perfect for both workout sessions and lounging around the house. Made with soft, durable fabric, these joggers feature a snug waistband, adjustable drawstring, and practical side pockets for functionality. Their tapered design and elastic cuffs offer a modern fit that keeps you looking stylish on the go.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/9LFjwpI.jpeg",
      "https://i.imgur.com/vzrTgUR.jpeg",
      "https://i.imgur.com/p5NdI6n.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 11,
    title: "Classic Red Baseball Cap",
    slug: "classic-red-baseball-cap",
    price: 35,
    description:
      "Elevate your casual wardrobe with this timeless red baseball cap. Crafted from durable fabric, it features a comfortable fit with an adjustable strap at the back, ensuring one size fits all. Perfect for sunny days or adding a sporty touch to your outfit.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/cBuLvBi.jpeg",
      "https://i.imgur.com/N1GkCIR.jpeg",
      "https://i.imgur.com/kKc9A5p.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
  {
    id: 12,
    title: "Classic Black Baseball Cap",
    slug: "classic-black-baseball-cap",
    price: 58,
    description:
      "Elevate your casual wear with this timeless black baseball cap. Made with high-quality, breathable fabric, it features an adjustable strap for the perfect fit. Whether you’re out for a jog or just running errands, this cap adds a touch of style to any outfit.",
    category: {
      id: 1,
      name: "Clothes",
      slug: "clothes",
      image: "https://i.imgur.com/QkIa5tT.jpeg",
      creationAt: "2025-10-17T19:29:51.000Z",
      updatedAt: "2025-10-17T19:29:51.000Z",
    },
    images: [
      "https://i.imgur.com/KeqG6r4.jpeg",
      "https://i.imgur.com/xGQOw3p.jpeg",
      "https://i.imgur.com/oO5OUjb.jpeg",
    ],
    creationAt: "2025-10-17T19:29:51.000Z",
    updatedAt: "2025-10-17T19:29:51.000Z",
  },
];
